// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGgRhX5i1mCv8yX0DiqdQr6ZgbNOstA5w',
    appId: '1:813445511325:web:52588e7313b144ce457c74',
    messagingSenderId: '813445511325',
    projectId: 'anynote-311cb',
    authDomain: 'anynote-311cb.firebaseapp.com',
    storageBucket: 'anynote-311cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdPi0IhsbXlhWhGuUOHWgopYLq6TCtOmE',
    appId: '1:813445511325:android:6d8122c326a9484b457c74',
    messagingSenderId: '813445511325',
    projectId: 'anynote-311cb',
    storageBucket: 'anynote-311cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-CikDGNWNRb076QCshG2NJYFnYA4bTY',
    appId: '1:813445511325:ios:b3709c0a60f37ad5457c74',
    messagingSenderId: '813445511325',
    projectId: 'anynote-311cb',
    storageBucket: 'anynote-311cb.appspot.com',
    iosClientId: '813445511325-et2947aguujfguetkrc4iq71fj488n3h.apps.googleusercontent.com',
    iosBundleId: 'com.abdulwasayimran.anyNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj-CikDGNWNRb076QCshG2NJYFnYA4bTY',
    appId: '1:813445511325:ios:b3709c0a60f37ad5457c74',
    messagingSenderId: '813445511325',
    projectId: 'anynote-311cb',
    storageBucket: 'anynote-311cb.appspot.com',
    iosClientId: '813445511325-et2947aguujfguetkrc4iq71fj488n3h.apps.googleusercontent.com',
    iosBundleId: 'com.abdulwasayimran.anyNote',
  );
}
